url: http://erikeng.se
title: "Erik Eng utvecklar för webb &amp; mobilt"
description: "Öppen källkod och tillgänglig data gör dagen intressant och webben bättre."
language: sv-se

author: "Erik Eng"
email: erik@eng.se
dribbble: ptz0n
instagram: ptz0n
twitter: ptz0n
flattr:
    user: ptz0n
    language: sv_SE
facebook:
    app: "481444638550896"
    posts: 5
    width: 500
    admins: "516158352"
analytics:
    profile: "33567818"

permalink: /post/:title.html
markdown: kramdown
timezone: "Europe/Paris"

future: false

exclude: ["README.md", "config.rb", "404.html", "node_modules", "Gemfile", "Gruntfile.js", "package.json"]

plugins: ["jekyll-sitemap", "jekyll-redirect-from"]
