url: http://erikeng.se
title: Erik Eng utvecklar för webb &amp; mobilt
description: Öppen källkod och tillgänglig data gör dagen intressant och webben bättre.
language: sv-se

author: Erik Eng
email: mail@ptz0n.se
github: ptz0n
twitter: ptz0n
dribbble: ptz0n
google: 105380157389113696457
flattr:
    user: ptz0n
    language: sv_SE
facebook:
    app: 481444638550896
    posts: 5
    width: 500
    admins: 516158352
analytics:
    profile: 33567818

permalink: /post/:title.html

future: false
auto: true
server: true

sitemap:
    include: ["/index.html"]

exclude: ["README.md", "config.rb"]