url: http://erikeng.se
title: Erik Eng utvecklar för webb &amp; mobilt
description: Öppen källkod och tillgänglig data gör dagen intressant och webben bättre.
language: sv-se

author: Erik Eng
email: mail@ptz0n.se
github: ptz0n
twitter: ptz0n
dribbble: ptz0n
flattr: ptz0n

permalink: /post/:title.html

future: false
auto: true
server: true

exclude: ["README.md", "config.rb"]